# Generated by Django 3.0.5 on 2020-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
