# Generated by Django 3.0.5 on 2020-04-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200426_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='zipcode',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
